server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/data
    username: root
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka

logging:
  level:
    com.innowise.orderservice: DEBUG
